#!/bin/bash
module load matlab/2015a
for n in {01..10}; do
    echo "n = $n;" >script${n}.m
    echo "sqrtn = sqrt(n);" >>script${n}.m
    echo "save('data${n}.txt', 'sqrtn', '-ascii');" \
        >>script${n}.m
    echo "quit" >>script${n}.m
    matlab -nojvm -r script${n} >/dev/null
    cat data${n}.txt
done
